name: AppImage

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Clone pkg2appimage
      run: |
        git clone https://github.com/AppImage/pkg2appimage 
        echo 0
    - name: Create AppImage
      run: |
        cd pkg2appimage
        ./pkg2appimage ../guiscrcpy/io.srevinsaju.guiscrcpy.yml
        echo 0
    - name: Upload AppImage
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: guiscrcpy.AppImage
        # Directory containing files to upload
        path: out/gui*.AppImage  
      
