name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt install libsnappy-dev libsqlite3-dev desktop-file-utils python3-virtualenv python3-venv
          pip3 install virtualenv
          sudo /usr/bin/easy_install virtualenv
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: get Bundle
        run: |
          git clone https://github.com/AppImage/pkg2appimage.git --depth=1
          cd pkg2appimage
          chmod +x ./pkg2appimage
          ./pkg2appimage ../io.srevinsaju.guiscrcpy.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: guiscrcpy.AppImage
          # Directory containing files to upload
          path: out/guiscrcpy*.AppImage
