name: Build AppImage
on: [push]

jobs:
  build:
    name: AppImage
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt install libsnappy-dev libsqlite3-dev
          wget https://github.com/AppImage/pkg2appimage/releases/download/continuous/pkg2appimage-continuous-x86_64.AppImage
          chmod +x *
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: get Bundle
        run: |
          ./pkg2appImage*.AppImage io.srevinsaju.guiscrcpy.yml
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: guiscrcpy.AppImage
          # Directory containing files to upload
          path: out/guiscrcpy*.AppImage
